return {
  { path = "shell/script.sh", ft = "sh", parser = "bash", lsp = { "bashls" }, format = "shfmt" },
  { path = "shell/.zshrc", ft = "zsh", parser = "bash", lsp = { "bashls" }, format = "shfmt" },
  { path = "yaml/config.yaml", ft = "yaml", parser = "yaml", lsp = { "yamlls" } },
  { path = "yaml/playbooks/site.yml", ft = "yaml.ansible", parser = "yaml", lsp = { "ansiblels" } },
  { path = "yaml/deployment.yaml", ft = "yaml", parser = "yaml", lsp = { "yamlls" } },
  { path = "ini/settings.ini", ft = "dosini", parser = "ini" },
  { path = "ini/foo.service", ft = "systemd", parser = "ini" },
  { path = "ssh/.ssh/config", ft = "sshconfig", syntax = true },
  { path = "log/app.log", ft = "log", syntax = true },
  {
    path = "text/notes.txt",
    ft = "text",
    syntax = true,
    note = "No Vale LSP expectation: it is not provisioned in the strict image.",
  },
  { path = "json/data.json", ft = "json", parser = "json", lsp = { "jsonls" }, format = "jsonls" },
  { path = "json/package.json", ft = "json", parser = "json", lsp = { "jsonls" }, format = "jsonls" },
  { path = "json/tsconfig.json", ft = "jsonc", parser = "jsonc", lsp = { "jsonls" }, format = "jsonls" },
  { path = "xml/pom.xml", ft = "xml", syntax = true },
  { path = "xml/Info.plist", ft = "xml", syntax = true },
  { path = "python/main.py", ft = "python", parser = "python", lsp = { "basedpyright", "ruff" }, format = "ruff" },
  {
    path = "python/test_sample.py",
    ft = "python",
    parser = "python",
    lsp = { "basedpyright", "ruff" },
    format = "ruff",
  },
  { path = "make/Makefile", ft = "make", parser = "make" },
  { path = "just/justfile", ft = "just", syntax = true, min_nvim = "0.10" },
  { path = "just/.justfile", ft = "just", syntax = true, min_nvim = "0.10" },
  { path = "markdown/README.md", ft = "markdown", parser = "markdown" },
  { path = "toml/Cargo.toml", ft = "toml", parser = "toml", lsp = { "taplo" } },
  { path = "git/.gitignore", ft = "gitignore", parser = "gitignore" },
  { path = "lua/init.lua", ft = "lua", parser = "lua", format = "stylua" },
  { path = "docker/Dockerfile", ft = "dockerfile", parser = "dockerfile", lsp = { "dockerls" } },
}
